### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by christopher-black**
Unit tests for assignment 4.1. Example output:

```
---
| Part 3 - Cart System | Complete? |
| --- | :---: |
 | Runs in browser without console errors | yes | 
 | Returns the string 'hello' | yes | 
 | Returns the string 'Hello, Your Name!' | no, see note 1 | 
 | Returns the sum of two numbers | no, see note 2 | 
 | Multiplies three numbers and returns the result | no, see note 3 | 
 | Should check if number is positive | no, see note 4 | 
 | Returns the last item in an Array | no, see note 5 | 
 | Finds an item in an Array | no, see note 6 | 


1) AssertionError: helloName() does not return anything: expected undefined to exist

2) AssertionError: addNumbers() does not return anything: expected undefined to exist

3) AssertionError: multiplyThree() does not return anything: expected undefined to exist

4) AssertionError: isPositive() does not return anything: expected undefined to exist

5) AssertionError: getLast() does not return anything: expected undefined to exist

6) AssertionError: find() does not return anything: expected undefined to exist
```

### CODE REVIEW

**Comment by aharasymiw** [comment]
assignment/scripts/function-practice.js

It looks like it got reformatted.
I'm not sure how picky we are are about that, but I seem to remember T1 assignment code all following similar formatting.  Other than that, amazing :)

**Comment by aharasymiw** [comment]
| Returns the string 'Hello, Your Name!' | no, see note 1 | 

I think this is fine, but I wonder if we want to move to checking if the output is a string that contains 'Hello', and ' ',  and 'Your Name', so we are more forgiving with punctuation, which isn't a requirement of the question, but rather a consistent example.

**Comment by aharasymiw** [comment]
| Returns the sum of two numbers | no, see note 2 | 

I don't think we can test this one, unless we change the existing code to take in a second argument.

**Comment by aharasymiw** [comment]
| Multiplies three numbers and returns the result | no, see note 3 | 

Similar to number two.
If adding arguments to the function definition is part of the problem they are intended to solve, maybe we need to clarify that.  Instead of `// 4. Function to multiply three numbers & return the result` something like `// 4. Function to take in three numbers, multiply them & return the result`.

**Comment by aharasymiw** [comment]
It might be nice to have, in index.html, to have a background color behind the link.
I have darkmode on, so the word "Refresh" is dark purple on black, and I couldn't read what it said, so was very confused for a while.

**Review by DoctorHowser — APPROVED** [review]

**Pull request merged**
